apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: web-replicaset
  name: web-replicaset
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: nginx:1.27-alpine
        name: web
