apiVersion: v1
kind: Pod
metadata:
  name: rbac-test
  namespace: default
spec:
  serviceAccountName: pod-reader-sa
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
