apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-env
spec:
  containers:
    - name: app
      image: busybox:latest
      command: ["sleep", "3600"]
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db.host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db.port
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app.environment
