apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 同じリモート base を参照
resources:
  - https://github.com/ono-hiroki/kustomize-base-example.git/bases/helloworld?ref=main

# 本番環境用のカスタマイズ
namePrefix: prod-

labels:
  - pairs:
      env: production
    includeSelectors: true

# レプリカ数を増やす
replicas:
  - name: hello-app
    count: 5

# イメージタグを変更
images:
  - name: nginx
    newTag: "1.26"

# パッチでリソースを追加
patches:
  - path: patches/deployment-patch.yaml
