apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomize 公式サンプルの helloWorld を参照
resources:
  - https://github.com/kubernetes-sigs/kustomize//examples/helloWorld?ref=master

# ローカルでカスタマイズ
namePrefix: dev-

commonLabels:
  env: development

# レプリカ数を変更
replicas:
  - name: the-deployment
    count: 2
