apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# リモートの base を参照
resources:
  - https://github.com/ono-hiroki/kustomize-base-example.git/bases/helloworld?ref=main

# ローカルでカスタマイズ
namePrefix: dev-

labels:
  - pairs:
      env: development
    includeSelectors: true

# レプリカ数を変更
replicas:
  - name: hello-app
    count: 2
